### ISSUE TITLE
ParaView 5.11+ Support

### ISSUE THREAD

**Issue by jwindgassen** [SENSEI-insitu/SENSEI#102]
According to the [CMake Files](https://github.com/SENSEI-insitu/SENSEI/blob/master/CMake/catalyst.cmake#L20), the current version is only compatible with ParaView 5.9 and 5.10. Have you already conducted tests with the new ParaView Version (5.11) or are you aware of any (potential) problems with it?
We are currently rolling out a new Software Stage and have to decide whether we also need to provide 5.10 or if 5.11 is sufficient.

**Comment by burlen** [comment]
We have not tested with ParaView 5.11. You're probably better of staying at 5.10.

**Comment by burlen** [comment]
See #108
