### ISSUE TITLE
ADIOS2 breaking C-API Changes

### ISSUE THREAD

**Issue by jwindgassen** [SENSEI-insitu/SENSEI#106]
The ADIOS2 support for the debug_mode flag was already removed some versions ago, now the C-API was already changed and the debug_mode parameter was removed from `adios2_init`. AFAIK these changes will be released with ADIOS2 2.9.0: https://github.com/ornladios/ADIOS2/issues/2127#issuecomment-1117234517. 
This will break SENSEI when it is compiled with any of those upcoming releases.

IMHO we can just remove these parameters from the corresponding classes. But the question remains what we do with the Setters in `ADIOS2DataAdaptor` and `ADIOS2AnalysisAdaptor`. Should we just remove them or are they important enough and we just print a warning when used?

**Comment by burlen** [comment]
Thanks for the heads up on this. When they release ADIOS 2.9 we:

1. update our code to use the new api and remove all the related setters and xml parsing etc from our classes
2. we change our CMake code to  `find_package(ADIOS2 REQUIRED VERSION 2.9)` to explicitly name the version we depend on

This change should wait until they release 2.9

**Comment by jwindgassen** [comment]
SGTM. I already implemented all the points from the first point (https://github.com/jwindgassen/SENSEI/commit/9212e495305aa3a293ae9efb6a76c0eab6db683f). I can also add the CMake changes and open a MR in the next few days.

**Comment by burlen** [comment]
this was resolved
