### ISSUE TITLE
Move Container to SENSEI docker hub repository

### ISSUE THREAD

**Issue by kwryankrattiger** [SENSEI-insitu/SENSEI#14]

**Comment by kwryankrattiger** [comment]
This will also need an update:
https://github.com/AMReX-Codes/amrex/pull/2115

**Comment by ax3l** [comment]
This will also need an update:
https://github.com/ECP-WarpX/WarpX/pull/2210

**Comment by burlen** [comment]
I believe this was completed. Please reopen if it was not.
