### ISSUE TITLE
SENSEI-5.0.0.tar.gz does not contain HAMR source

### ISSUE THREAD

**Issue by danlipsa** [SENSEI-insitu/SENSEI#145]
After downloading SENSEI-5.0.0.tar.gz
```
[~/Downloads]$ tar xzf SENSEI-5.0.0.tar.gz 
[~/Downloads]$ ls -l SENSEI-5.0.0/utils/HAMR
total 0
```

**Comment by kwryankrattiger** [comment]
I am guessing we need to do what we do for ParaView and generate the tarball from a copy of the source with the submodule cloned.

The way the release process is supposed to work is to build a tarball manually that contains all of the required source in it and upload it separately.

**Comment by danlipsa** [comment]
Indeed. So how do we fix this? It is fairly easy to re-upload the right tar.gz.

**Comment by danlipsa** [comment]
@burlen Any suggestions? Thanks!

**Comment by danlipsa** [comment]
Thanks @kwryankrattiger for uploading the corrected tgz

**Comment by danlipsa** [comment]
@kwryankrattiger We would want to update v5.0.0.tar.gz and v5.0.0.zip files as well. (or delete them) because they are the version without the HAMR source (at least the tar.gz is).

**Comment by kwryankrattiger** [comment]
> We would want to update v5.0.0.tar.gz and v5.0.0.zip files as well. (or delete them) because they are the version without the HAMR source (at least the tar.gz is).

Those are automatically populated by github based on the tag. I don't know how to disable those.

**Comment by danlipsa** [comment]
Somehow, those were updated 2 weeks ago (so they are the wrong versions) while SENSEI-5.0.0.tar.gz was updated yesterday.

**Comment by kwryankrattiger** [comment]
Two weeks ago that tag was pushed, which generated those tarballs automatically. I uploaded the SENSE-5.0.0.tar.gz yesterday generated from the source associated with that tag.

**Comment by danlipsa** [comment]
Oh, I see. So tagging triggered something on github that build those packages. Unfortunately it built them wrong because it does not account for git submodules

**Comment by kwryankrattiger** [comment]
Right, here is a discussion about disabling the feature but no updates redcently: https://github.com/orgs/community/discussions/6003
