### ISSUE TITLE
Deprecating MultiBlock Datasets?

### ISSUE THREAD

**Issue by mvictoras** [SENSEI-insitu/SENSEI#26]
Looks like Kitware will deprecate MultiBlock datasets:
https://discourse.paraview.org/t/deprecating-multiblock-datasets/4950

Any thoughts/comments on what direction we will follow?

**Comment by burlen** [comment]
I don't see the benefit of rewriting everything to make use of the new datasets. It will be a lot effort that would be better spent on science facing codes, bi-driectional implementation, heterogeneous processing etc.

One motivation for forking & mangling VTK is to isolate SENSEI from such changes. ParaView can do what makes sense for it, VisIt can do something else, and we won't be impacted.
