### ISSUE TITLE
VTKObjectFactory not working for svtkUnstructuredGrid

### ISSUE THREAD

**Issue by hpcdgrie** [SENSEI-insitu/SENSEI#48]
In 
vtkUnsignedCharArray *ct =    static_cast<vtkUnsignedCharArray*>(VTKObjectFactory::New(ugIn->GetCellTypesArray()));
the dynamic_cast fails because VTKObjectFactory::New(svtkUnsignedCharArray) actually returns a vtkSOADataArrayTemplate<unsigned char>. Static_cast works for me, but I don't know if it is save.

Also only copying the vtkPointData seems not enough. Also copying the vtkPoints fixed it for me:
  auto points = VTKObjectFactory::New(ugIn->GetPoints());
  if (!points)
  {
    SENSEI_ERROR("Failed to transfer points")
    ugOut->Delete();
    return nullptr;
  }
  ugOut->SetPoints(points);
  points->Delete();

**Comment by burlen** [comment]
@hpcdgrie thanks for the report, please reopen the issue if you continue to experience these problems.
