### ISSUE TITLE
CMake: Wrong Config Install Path

### ISSUE THREAD

**Issue by ax3l** [SENSEI-insitu/SENSEI#79]
Hi,

As of SENSEI 4.0, the SENSEI CMake config packages are installed in the wrong location.

On Ubuntu, I find them under `lib[64]/cmake` instead of `lib[64]/cmake/sensei`, which breaks the standard CMake `find_package` order:
https://cmake.org/cmake/help/v3.24/command/find_package.html#config-mode-search-procedure

Note that you need to either use a more universal path above or add extra handling if you also like to support Windows.

The current bug makes development harder for WarpX devs and requires work-arounds in package managers, see e.g. https://github.com/spack/spack/pull/31542

**Comment by burlen** [comment]
fixed in #80
