### ISSUE TITLE
SWIG directive "%ignore" misspelled as "%ingnore"

### ISSUE THREAD

**Issue by player1537** [SENSEI-insitu/SENSEI#90]
I'm not sure how I haven't run into this before, but I just found a typo within the `src/DataAdaptor.i` file where `%ingnore` is written instead of `%ignore`. This caused a compilation error for me.

I'm not sure if it matters, but this occurred when compiling with `-DPython3_EXECUTABLE=$(which python3.11)`. I didn't have any other CMake variables set.

**Comment by burlen** [comment]
Thank you for the report. This issue was fixed recently and is available on the `develop` branch.

**Comment by burlen** [comment]
resolved in #86
