### ISSUE TITLE
SENSEI version should not be forced

### ISSUE THREAD

**Issue by burlen** [SENSEI-insitu/SENSEI#91]
See: https://github.com/SENSEI-insitu/SENSEI/commit/bbc5178dc2625cda5e2508dd70ee4302bf06e5b6#commitcomment-92952252

SENSEI_VERSION is a cache variable so once it's set it set for ever. This becomes problematic over time as the version is not accurate without a fresh build as one incrementally pulls changes from upstream. 

Another problem is that FORCE modifier means that it cannot be overridden. A user has requested that it be overridable.

Would making this an un-cached variable solve the problem?

**Comment by kwryankrattiger** [comment]
Setting it as cache does not mean it is that value forever. It can be updated by running `cmake -DSENSEI_VERSION="4.4.4" .`

A method for getting the current tag version all the time is to set the default to "<DEFAULT>" and then setting it in the CMake scope which is similar to force, but handles the case where users don't want to use the default.

```cmake
set(SENSEI_VERSION "<DEFAULT>" CACHE STRING "SENSEI Version")
if (SENSEI_VERSION MATCHES "<DEFAULT>")
  # ...Try to get version from git, or hard-coded default
  set(SENSEI_VERSION ${computed_version})
endif ()
```

In the `CMakeCache.txt` it will appear as `"<DEFAULT>"`, but to the CMake configuration it will populate as the `${computed_version}` overriding the CACHE value locally.

If it does not appear as `"<DEFAULT>"` it will use the CACHE value as the version.

**Comment by burlen** [comment]
The part about it lasting forever applies to when the value is not specified on the command line. Take the case where my clone and it's build has been around for a number of months and we've recently made a release. The cache variable does not get updated to the latest version without the FORCE. The point of adding FORCE was for a rolling refresh the version in existing clone/build scenario.

Having a hard coded value for the version either from the command line or in the cmake code itself defeats the purpose of the automatic versioning.

TODO : test if this needs to be a cached value.

Alternative: There is a way to query the tags of a remote that doesn't require a clone, it only requires git.  The problem here would be that how to we know which tag to use?
```
git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' git@github.com:SENSEI-insitu/SENSEI.git
```

**Comment by kwryankrattiger** [comment]
The example code solves that issue. The CACHE, without command line change, cannot change. To get around this behavior if you want to use the auto detection of the version transiently is to set the default cache to a keyword, some projects use `"<DEFAULT>"`, and if that is set override the CACHE locally in the cmake with a computed version. I will just PR the change so you/user can try it out.

**Comment by burlen** [comment]
OK, but then people using the tarball will still need to set the value on the command line. That seems problematic as well..

**Comment by burlen** [comment]
Another idea is to get rid of the tarballs on github altogether. as far as I can tell they are not needed. one could acheive the same thing with git clone, the head of the default branch(master) has the latest release

**Comment by kwryankrattiger** [comment]
VERSION should be cached if it is something that SENSEI wants to allow the user to change. The reason it had to be manually specified in the first place was to handle the tarball source builds. 

If the last release version gets updated correctly during releases then that is less of an issue going forward and it can just be an internal configuration detail, which I would really prefer. The patch that I pushed for version detection would then work without the cache variable and just using the code inside of the `if...endif` block.

**Comment by kwryankrattiger** [comment]
The tarballs are preferred for spack, cloning git is not a great method to get source.

**Comment by burlen** [comment]
hmm. why are tarballs preferred? you have to get the tarball form somewhere? wget or curl to fetch the traball, git clone to fetch the same source code. to me this appears to be doing the same using a different command

**Comment by burlen** [comment]
One reason to prefer a tarball over a clone is if the tarball is different than the clone. I know of a number of autotools based libraries for which that is the case. for sensei that is not the case though

**Comment by kwryankrattiger** [comment]
Git clones generally carry additional overhead than downloading a compressed tarball containing only the source required. Tags are also ignored when doing shallow clones of a single target branch iirc. so the detection would not work.

**Comment by burlen** [comment]
hmm. it may indeed be larger since the tarball is usually compressed. However, the detection works for me with the following command:
```
git clone --depth 1 --branch v4.0.0 git@github.com:SENSEI-insitu/SENSEI.git
```

**Comment by burlen** [comment]
either way I'd like test your PR

**Comment by burlen** [comment]
The above also works with `--branch master` rather than a specific tag
